[project]
name = "tmx-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.3",
    "fastapi[standard]>=0.115.11",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.0",
]
